package bitfinex

// Some of the more available paris. See https://api.bitfinex.com/v1/symbols for
// an up to date list

const (
	BTCUSD = "BTCUSD"
	BTCFUSTF = "BTCF0:USTF0"
	BTCEUR = "BTCEUR"
	BTCJPY = "BTCJPY"
	BTCUST = "BTCUST"

	LTCUSD = "LTCUSD"
	LTCBTC = "LTCBTC"
	LTCUST = "LTCUST"

	ETHUSD = "ETHUSD"
	ETHFUSTF ="ETHF0:USTF0"
	ETHBTC = "ETHBTC"
	ETHEUR = "ETHEUR"
	ETHJPY = "ETHJPY"
	ETHGBP = "ETHGBP"
	ETHUST = "ETHUST"

	ETCUSD = "ETCUSD"
	ETCBTC = "ETCBTC"
	ETCUST = "ETCUST"
	
	ZECUSD = "ZECUSD"
	ZECBTC = "ZECBTC"

	XMRUSD = "XMRUSD"
	XMRBTC = "XMRBTC"
	XMRUST = "XMRUST"

	RRTUSD = "RRTUSD"
	RRTBTC = "RRTBTC"

	XRPUSD = "XRPUSD"
	XRPBTC = "XRPBTC"
	XRPUST = "XRPUST"

	EOSETH = "EOSETH"
	EOSUSD = "EOSUSD"
	EOSBTC = "EOSBTC"
	EOSEUR = "EOSEUR"
	EOSJPY = "EOSJPY"
	EOSGBP = "EOSGBP"

	NEOUSD = "NEOUSD"
	NEOBTC = "NEOBTC"
	NEOETH = "NEOETH"

	TRXUSD = "TRXUSD"
	TRXBTC = "TRXBTC"
	TRXETH = "TRXETH"

	IOTUSD = "IOTUSD"
	IOTBTC = "IOTBTC"
	IOTETH = "IOTETH"
	IOTEUR = "IOTEUR"
	IOTJPY = "IOTJPY"
	IOTGBP = "IOTGBP"

	LEOUSD = "LEOUSD"
	LEOBTC = "LEOBTC"
	LEOUST = "LEOUST"
	LEOEOS = "LEOEOS"
	LEOETH = "LEOETH"

	DOTUSD = "DOTUSD"
	DOTUST = "DOTUST"

	ADAUSD = "ADAUSD"
	ADABTC = "ADABTC"
	ADAUST = "ADAUST"

	FETUSD = "FETUSD"
	FETUST = "FETUST"
	
	LINKUSD = "LINK:USD"
	LINKUST = "LINK:UST"

	COMPUSD = "COMP:USD"
	COMPUST = "COMP:UST"
	
	UNIUSD = "UNIUSD"
	UNIUST = "UNIUST"

	AVAXUSD = "AVAX:USD"
	AVAXUST = "AVAX:UST"

	BCHUSD = "BCHN:USD"
	BCHUST = "BCHN:UST"

	AAVEUSD = "AAVE:USD"
	AAVEUST = "AAVE:UST"

	YFIUSD = "YFIUSD"
	YFIUST = "YFIUST"

	MKRUST = "MKRUST"
	MKRUSD = "MKRUSD"

	CRVUSD = "CRVUSD"
	CRVUST = "CRVUST"

	SOLUSD = "SOLUSD"
	SOLUST = "SOLUST"

	ATOMUSD = "ATOMUSD"
	ATOMUST = "ATOMUST"
	
	MATICUSD = "MATIC:USD"
	MATICUST = "MATIC:UST"
	MATICBTC = "MATIC:BTC"

	XLMUSD = "XLMUSD"
	XLMUST = "XLMUST"
	XLMBTC = "XLM:BTC"
	
)
